version: "3.8"
services:
  mysqldb:
    image: mysql:5.7
    restart: unless-stopped
    env_file: ./.env
    environment:
      - MYSQL_ROOT_PASSWORD=$DB_PASSWORD
      - MYSQL_DATABASE=$DB_NAME
    ports:
      - $DB_PORT:$DB_PORT
    volumes:
      - db:/var/lib/mysql
  redis:
    image: redis
    command: redis-server --appendonly yes --requirepass $REDIS_PASSWORD
    ports:
      - $REDIS_PORT:$REDIS_PORT
    volumes: 
      - cache:/data
  app:
    depends_on:
      - mysqldb
      - redis
    build: .
    restart: unless-stopped
    env_file: ./.env
    ports:
      - $PORT:$PORT
    environment:
      - DB_HOST=mysqldb
      - DB_USER=$DB_USER
      - DB_PASSWORD=$DB_PASSWORD
      - DB_NAME=$DB_NAME
      - DB_PORT=$DB_PORT
      - REDIS_HOST=redis
      - REDIS_PORT=$REDIS_PORT
      - REDIS_DATABASE=$REDIS_DATABASE
      - REDIS_PASSWORD=$REDIS_PASSWORD
    stdin_open: true
    tty: true
    volumes:
        - .:/usr/src/app
    command: npm run start:dev
volumes:
  db:
  cache: